apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gpt-be-65c867c744-6gtft
  namespace: danna-lopez-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gpt-be
  template:
    metadata:
      labels:
        app: api-gpt-be
    spec:
      containers:
      - name: api-gpt-be
        image: dannalopez/hackatonbe:latest
        ports:
        - containerPort: 30001
